/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author misbah
 */


    /**
     * Creates new form NewJFrame
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
package cal50;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

public class NewJFrame
  extends JFrame
{
  private double ans = 0.0D;
  private double x;
  private double y;
  private int c = 30;
  private int min = 0;
  private int p1;
  private int p2;
  private String str = " ";
  private String str1 = "0";
  private JButton abs1;
  private JButton clearC;
  private JButton cosa;
  private JButton div1;
  private JButton eql5;
  private JButton exit2;
  private JButton exp1;
  private JTextField inputF;
  private JButton it0;
  private JButton it1;
  private JButton it2;
  private JButton it3;
  private JButton it4;
  private JButton it5;
  private JButton it6;
  private JButton it7;
  private JButton it8;
  private JButton it9;
  private JButton itAns;
  private JPanel jPanel1;
  private JPanel jPanel2;
  private JPanel jPanel3;
  private JButton loga;
  private JButton min56;
  private JButton mul1;
  private JButton plus1;
  private JButton point1;
  private JButton pw1;
  private JButton sina;
  private JButton sqrt1;
  private JButton tana;
  
  public NewJFrame()
  {
    super("misbah.Calculator");
    
    initComponents();
  }
  
  private void initComponents()
  {
    this.jPanel2 = new JPanel();
    this.jPanel1 = new JPanel();
    this.it1 = new JButton();
    this.it8 = new JButton();
    this.it5 = new JButton();
    this.it2 = new JButton();
    this.it0 = new JButton();
    this.it9 = new JButton();
    this.it6 = new JButton();
    this.it3 = new JButton();
    this.point1 = new JButton();
    this.itAns = new JButton();
    this.mul1 = new JButton();
    this.exit2 = new JButton();
    this.clearC = new JButton();
    this.div1 = new JButton();
    this.plus1 = new JButton();
    this.min56 = new JButton();
    this.it7 = new JButton();
    this.it4 = new JButton();
    this.eql5 = new JButton();
    this.sina = new JButton();
    this.exp1 = new JButton();
    this.abs1 = new JButton();
    this.loga = new JButton();
    this.cosa = new JButton();
    this.tana = new JButton();
    this.pw1 = new JButton();
    this.sqrt1 = new JButton();
    this.jPanel3 = new JPanel();
    this.inputF = new JTextField();
    
    GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
    this.jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(jPanel2Layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 100, 32767));
    
    jPanel2Layout.setVerticalGroup(jPanel2Layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 100, 32767));
    
    setDefaultCloseOperation(3);
    
    this.jPanel1.setBackground(new Color(0, 0, 0));
    this.jPanel1.setForeground(new Color(0, 0, 204));
    
    this.it1.setBackground(new Color(102, 102, 102));
    this.it1.setText("1");
    this.it1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it1ActionPerformed(evt);
      }
    });
    this.it8.setBackground(new Color(102, 102, 102));
    this.it8.setText("8");
    this.it8.setToolTipText("eight");
    this.it8.setBorder(null);
    this.it8.setMaximumSize(new Dimension(39, 23));
    this.it8.setMinimumSize(new Dimension(39, 23));
    this.it8.setPreferredSize(new Dimension(39, 23));
    this.it8.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it8ActionPerformed(evt);
      }
    });
    this.it5.setBackground(new Color(102, 102, 102));
    this.it5.setText("5");
    this.it5.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it5ActionPerformed(evt);
      }
    });
    this.it2.setBackground(new Color(102, 102, 102));
    this.it2.setText("2");
    this.it2.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it2ActionPerformed(evt);
      }
    });
    this.it0.setBackground(new Color(102, 102, 102));
    this.it0.setText("0");
    this.it0.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it0ActionPerformed(evt);
      }
    });
    this.it9.setBackground(new Color(102, 102, 102));
    this.it9.setText("9");
    this.it9.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it9ActionPerformed(evt);
      }
    });
    this.it6.setBackground(new Color(102, 102, 102));
    this.it6.setText("6");
    this.it6.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it6ActionPerformed(evt);
      }
    });
    this.it3.setBackground(new Color(102, 102, 102));
    this.it3.setText("3");
    this.it3.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it3ActionPerformed(evt);
      }
    });
    this.point1.setBackground(new Color(102, 102, 102));
    this.point1.setForeground(new Color(0, 0, 204));
    this.point1.setText(".");
    this.point1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.point1ActionPerformed(evt);
      }
    });
    this.itAns.setBackground(new Color(102, 102, 102));
    this.itAns.setText("Ans");
    this.itAns.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.itAnsActionPerformed(evt);
      }
    });
    this.mul1.setBackground(new Color(102, 102, 102));
    this.mul1.setText("*");
    this.mul1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.mul1ActionPerformed(evt);
      }
    });
    this.exit2.setBackground(new Color(102, 102, 102));
    this.exit2.setText("Exit");
    this.exit2.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.exit2ActionPerformed(evt);
      }
    });
    this.clearC.setBackground(new Color(102, 102, 102));
    this.clearC.setText("c");
    this.clearC.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.clearCActionPerformed(evt);
      }
    });
    this.div1.setBackground(new Color(102, 102, 102));
    this.div1.setText("/");
    this.div1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.div1ActionPerformed(evt);
      }
    });
    this.plus1.setBackground(new Color(102, 102, 102));
    this.plus1.setText("+");
    this.plus1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.plus1ActionPerformed(evt);
      }
    });
    this.min56.setBackground(new Color(102, 102, 102));
    this.min56.setText("-");
    this.min56.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.min56ActionPerformed(evt);
      }
    });
    this.it7.setBackground(new Color(102, 102, 102));
    this.it7.setText("7");
    this.it7.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it7ActionPerformed(evt);
      }
    });
    this.it4.setBackground(new Color(102, 102, 102));
    this.it4.setText("4");
    this.it4.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.it4ActionPerformed(evt);
      }
    });
    this.eql5.setBackground(new Color(102, 102, 102));
    this.eql5.setText("=");
    this.eql5.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.eql5ActionPerformed(evt);
      }
    });
    this.sina.setBackground(new Color(102, 102, 102));
    this.sina.setText("sin");
    this.sina.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.sinaActionPerformed(evt);
      }
    });
    this.exp1.setBackground(new Color(102, 102, 102));
    this.exp1.setText("e");
    this.exp1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.exp1ActionPerformed(evt);
      }
    });
    this.abs1.setBackground(new Color(102, 102, 102));
    this.abs1.setText("abs");
    this.abs1.setMaximumSize(new Dimension(51, 23));
    this.abs1.setMinimumSize(new Dimension(51, 23));
    this.abs1.setPreferredSize(new Dimension(51, 23));
    this.abs1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.abs1ActionPerformed(evt);
      }
    });
    this.loga.setBackground(new Color(102, 102, 102));
    this.loga.setText("log");
    this.loga.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.logaActionPerformed(evt);
      }
    });
    this.cosa.setBackground(new Color(102, 102, 102));
    this.cosa.setText("cos");
    this.cosa.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.cosaActionPerformed(evt);
      }
    });
    this.tana.setBackground(new Color(102, 102, 102));
    this.tana.setText("tan");
    this.tana.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.tanaActionPerformed(evt);
      }
    });
    this.pw1.setBackground(new Color(102, 102, 102));
    this.pw1.setText("^");
    this.pw1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.pw1ActionPerformed(evt);
      }
    });
    this.sqrt1.setBackground(new Color(102, 102, 102));
    this.sqrt1.setText("sqrt");
    this.sqrt1.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.sqrt1ActionPerformed(evt);
      }
    });
    this.jPanel3.setBackground(new Color(0, 0, 0));
    
    this.inputF.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        NewJFrame.this.inputFActionPerformed(evt);
      }
    });
    GroupLayout jPanel3Layout = new GroupLayout(this.jPanel3);
    this.jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(jPanel3Layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
      .addGap(26, 26, 26)
      .addComponent(this.inputF, -2, 305, -2)
      .addContainerGap(-1, 32767)));
    
    jPanel3Layout.setVerticalGroup(jPanel3Layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
      .addContainerGap()
      .addComponent(this.inputF, -1, 36, 32767)
      .addGap(19, 19, 19)));
    
    GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
    this.jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(jPanel1Layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
      .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.sina, -1, -1, 32767)
      .addComponent(this.cosa, -1, 65, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.tana, -1, 99, 32767)
      .addComponent(this.loga, -1, -1, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.exp1, -1, -1, 32767)
      .addComponent(this.pw1, -1, 100, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.abs1, -1, 63, 32767)
      .addComponent(this.sqrt1, -1, -1, 32767)))
      .addGroup(jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.it0, -1, -1, 32767)
      .addComponent(this.it7, -1, -1, 32767)
      .addComponent(this.it1, -1, -1, 32767)
      .addComponent(this.it4, -1, -1, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.point1, -1, 65, 32767)
      .addComponent(this.it5, -1, 65, 32767)
      .addComponent(this.it2, -1, -1, 32767)
      .addComponent(this.it8, -1, -1, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
      .addComponent(this.it9, -1, 65, 32767)
      .addComponent(this.it3, -1, 58, 32767)
      .addComponent(this.itAns, -1, 58, 32767)
      .addComponent(this.it6, -1, -1, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(this.plus1, -2, 53, -2)
      .addComponent(this.clearC, -2, 56, -2)
      .addComponent(this.mul1, -1, -1, 32767))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(this.div1, -1, -1, 32767)
      .addComponent(this.min56, -1, -1, 32767)
      .addComponent(this.exit2, -1, 65, 32767)))
      .addGroup(jPanel1Layout.createSequentialGroup()
      .addGap(20, 20, 20)
      .addComponent(this.eql5, -2, 97, -2)))))
      .addContainerGap(-1, 32767))
      .addComponent(this.jPanel3, -1, -1, 32767));
    
    jPanel1Layout.linkSize(0, new Component[] { this.it0, this.it2, this.it3, this.itAns, this.point1 });
    
    jPanel1Layout.linkSize(0, new Component[] { this.it1, this.it4, this.it5, this.it7, this.it8 });
    
    jPanel1Layout.linkSize(0, new Component[] { this.clearC, this.div1, this.exit2, this.it9, this.min56, this.mul1, this.plus1 });
    
    jPanel1Layout.setVerticalGroup(jPanel1Layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
      .addContainerGap(-1, 32767)
      .addComponent(this.jPanel3, -2, -1, -2)
      .addGap(52, 52, 52)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
      .addComponent(this.sina, -2, 38, -2)
      .addComponent(this.tana)
      .addComponent(this.pw1)
      .addComponent(this.sqrt1, -2, 38, -2))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
      .addComponent(this.abs1, -1, -1, 32767)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
      .addComponent(this.exp1)
      .addComponent(this.loga)
      .addComponent(this.cosa)))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
      .addComponent(this.it7, -2, 46, -2)
      .addComponent(this.it8, -2, 46, -2)
      .addComponent(this.it9, -2, 38, -2)
      .addComponent(this.clearC)
      .addComponent(this.exit2))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
      .addComponent(this.it5)
      .addComponent(this.it6)
      .addComponent(this.div1)
      .addComponent(this.it4, -2, 38, -2)
      .addComponent(this.mul1))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
      .addComponent(this.it2)
      .addComponent(this.it3)
      .addComponent(this.min56)
      .addComponent(this.it1)
      .addComponent(this.plus1, -2, 44, -2))
      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
      .addComponent(this.it0)
      .addComponent(this.point1)
      .addComponent(this.itAns)
      .addComponent(this.eql5, -2, 46, -2))
      .addGap(28, 28, 28)));
    
    jPanel1Layout.linkSize(1, new Component[] { this.clearC, this.div1, this.exit2, this.it0, this.it1, this.it2, this.it3, this.it4, this.it5, this.it6, this.it7, this.it8, this.it9, this.itAns, this.min56, this.mul1, this.plus1, this.point1 });
    
    jPanel1Layout.linkSize(1, new Component[] { this.cosa, this.exp1, this.loga, this.pw1, this.sina, this.sqrt1, this.tana });
    
    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(this.jPanel1, -2, -1, -2));
    
    layout.setVerticalGroup(layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(this.jPanel1, -1, -1, 32767));
    
    pack();
  }
  
  private void it4ActionPerformed(ActionEvent evt)
  {
    this.str += "4";
    this.inputF.setText(this.str);
    this.str1 += "4";
  }
  
  private void it7ActionPerformed(ActionEvent evt)
  {
    this.str += "7";
    this.inputF.setText(this.str);
    this.str1 += "7";
  }
  
  private void clearCActionPerformed(ActionEvent evt)
  {
    this.str = "";
    this.inputF.setText(this.str);
    this.str1 = "0";
    this.ans = 0.0D;
    this.c = 30;
  }
  
  private void it8ActionPerformed(ActionEvent evt)
  {
    this.str += "8";
    this.inputF.setText(this.str);
    this.str1 += "8";
  }
  
  private void it9ActionPerformed(ActionEvent evt)
  {
    this.str += "9";
    this.inputF.setText(this.str);
    this.str1 += "9";
  }
  
  private void plus1ActionPerformed(ActionEvent evt)
  {
    this.str += "+";
    this.inputF.setText(this.str);
    this.x = Double.parseDouble(this.str1);
    if (this.c == 1)
    {
      this.ans -= this.x;
      
      this.c = 0;
    }
    else if (this.c == 3)
    {
      this.ans *= this.x;
      
      this.c = 0;
    }
    else if (this.c == 15)
    {
      this.ans /= this.x;
      
      this.c = 0;
    }
    else
    {
      this.ans += this.x;
      
      this.c = 0;
    }
    this.str1 = "0";
  }
  
  private void it6ActionPerformed(ActionEvent evt)
  {
    this.str += "6";
    this.inputF.setText(this.str);
    this.str1 += "6";
  }
  
  private void it5ActionPerformed(ActionEvent evt)
  {
    this.str += "5";
    this.inputF.setText(this.str);
    this.str1 += "5";
  }
  
  private void pw1ActionPerformed(ActionEvent evt)
  {
    this.p1 = Integer.parseInt(this.str1);
    this.str += "^";
    this.inputF.setText(this.str);
    this.str1 = "0";
    this.c = 10;
  }
  
  private void min56ActionPerformed(ActionEvent evt)
  {
    this.str += "-";
    this.inputF.setText(this.str);
    this.x = Double.parseDouble(this.str1);
    if ((this.c != 3) && (this.c != 15)) {
      if (this.c != -13)
      {
        if (this.x == 0.0D) {
          this.c = 1;
        }
        if (this.c != 0)
        {
          if (this.x != 0.0D)
          {
            if (this.min == 1)
            {
              this.ans = (-this.x);
              this.min = 0;
              this.str1 = "0";
            }
            else if (this.ans == 0.0D)
            {
              this.ans = (this.x - this.ans);
              this.str1 = "0";
            }
            else
            {
              this.ans -= this.x;
              this.str1 = "0";
            }
          }
          else
          {
            this.min = 1;
            this.str1 = "0";
          }
        }
        else
        {
          this.ans += this.x;
          this.str1 = "0";
        }
        this.c = 1;
      }
      else
      {
        this.c = -13;
      }
    }
    if ((this.c == 3) || (this.c == 15))
    {
      if (this.c == 3)
      {
        this.ans *= this.x;
        
        this.c = 1;
        this.str1 = "0";
      }
      if (this.c == 15)
      {
        this.ans /= this.x;
        
        this.c = 1;
        this.str1 = "0";
      }
    }
  }
  
  private void mul1ActionPerformed(ActionEvent evt)
  {
    this.x = Double.parseDouble(this.str1);
    if (this.ans == 0.0D)
    {
      this.ans = this.x;
      this.str += "*";
      this.inputF.setText(this.str);
      this.str1 = "0";
    }
    else if (this.c == 1)
    {
      this.ans -= this.x;
      this.str += "*";
      this.inputF.setText(this.str);
      this.str1 = "0";
      this.c = 3;
    }
    else if (this.c == 0)
    {
      this.ans += this.x;
      this.str += "*";
      this.inputF.setText(this.str);
      
      this.str1 = "0";
    }
    else if (this.c == 15)
    {
      this.ans /= this.x;
      this.str += "*";
      this.inputF.setText(this.str);
      
      this.str1 = "0";
    }
    else
    {
      this.str += "*";
      this.inputF.setText(this.str);
      this.str1 = "0";
    }
    this.c = 3;
  }
  
  private void it1ActionPerformed(ActionEvent evt)
  {
    this.str += "1";
    this.inputF.setText(this.str);
    this.str1 += "1";
  }
  
  private void point1ActionPerformed(ActionEvent evt)
  {
    this.str += ".";
    this.inputF.setText(this.str);
    this.str1 += ".";
  }
  
  private void it0ActionPerformed(ActionEvent evt)
  {
    this.str += "0";
    this.inputF.setText(this.str);
    this.str1 += "0";
  }
  
  private void it2ActionPerformed(ActionEvent evt)
  {
    this.str += "2";
    this.inputF.setText(this.str);
    this.str1 += "2";
  }
  
  private void it3ActionPerformed(ActionEvent evt)
  {
    this.str += "3";
    this.inputF.setText(this.str);
    this.str1 += "3";
  }
  
  private void eql5ActionPerformed(ActionEvent evt)
  {
    if (this.c == 0)
    {
      this.y = Double.parseDouble(this.str1);
      
      this.ans += this.y;
      
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 1)
    {
      this.y = Double.parseDouble(this.str1);
      
      this.ans -= this.y;
      
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 5)
    {
      this.y = Double.parseDouble(this.str1);
      this.ans = StrictMath.sin(Math.toRadians(this.y));
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 6)
    {
      this.y = Double.parseDouble(this.str1);
      this.ans = StrictMath.cos(Math.toRadians(this.y));
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 7)
    {
      this.y = Double.parseDouble(this.str1);
      this.ans = StrictMath.tan(Math.toRadians(this.y));
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 8)
    {
      this.y = Double.parseDouble(this.str1);
      this.ans = StrictMath.log10(this.y);
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 9)
    {
      this.y = Double.parseDouble(this.str1);
      this.ans = StrictMath.exp(this.y);
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 10)
    {
      this.p2 = Integer.parseInt(this.str1);
      this.ans = StrictMath.pow(this.p1, this.p2);
      this.inputF.setText(this.str + " = " + (int)this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == 11)
    {
      this.y = Double.parseDouble(this.str1);
      
      this.ans = StrictMath.sqrt(this.y);
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
    }
    if (this.c == -13)
    {
      this.y = 0.0D;
      this.y = Double.parseDouble(this.str1);
      
      this.ans = Math.abs(this.y);
      
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      
      this.str1 = "0";
      this.c = 50;
    }
    if (this.c == 3)
    {
      this.y = Double.parseDouble(this.str1);
      
      this.ans *= this.y;
      
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      this.str1 = "0";
      this.c = 50;
    }
    if (this.c == 15)
    {
      this.y = Double.parseDouble(this.str1);
      
      this.ans /= this.y;
      
      this.inputF.setText(this.str + " = " + this.ans);
      
      this.str = (this.str + " = " + this.ans);
      this.str1 = "0";
      this.c = 50;
    }
  }
  
  private void exp1ActionPerformed(ActionEvent evt)
  {
    this.str += "e^";
    this.inputF.setText(this.str);
    this.c = 9;
  }
  
  private void inputFActionPerformed(ActionEvent evt) {}
  
  private void sinaActionPerformed(ActionEvent evt)
  {
    this.str += "sin ";
    this.inputF.setText(this.str);
    this.c = 5;
  }
  
  private void cosaActionPerformed(ActionEvent evt)
  {
    this.str += "cos ";
    this.inputF.setText(this.str);
    this.c = 6;
  }
  
  private void tanaActionPerformed(ActionEvent evt)
  {
    this.str += "tan ";
    this.inputF.setText(this.str);
    this.c = 7;
  }
  
  private void exit2ActionPerformed(ActionEvent evt)
  {
    System.exit(0);
  }
  
  private void logaActionPerformed(ActionEvent evt)
  {
    this.str += "log ";
    this.inputF.setText(this.str);
    this.c = 8;
  }
  
  private void sqrt1ActionPerformed(ActionEvent evt)
  {
    this.str += "sqrt ";
    this.inputF.setText(this.str);
    this.str1 = "0";
    this.c = 11;
  }
  
  private void abs1ActionPerformed(ActionEvent evt)
  {
    this.str += "Abs ";
    this.inputF.setText(this.str);
    this.str1 = "0";
    this.c = -13;
  }
  
  private void div1ActionPerformed(ActionEvent evt)
  {
    this.x = Double.parseDouble(this.str1);
    if (this.ans == 0.0D)
    {
      this.ans = this.x;
      this.str += "/";
      this.inputF.setText(this.str);
      this.str1 = "0";
    }
    else if (this.c == 1)
    {
      this.ans -= this.x;
      this.str += "/";
      this.inputF.setText(this.str);
      this.str1 = "0";
    }
    else if (this.c == 0)
    {
      this.ans += this.x;
      this.str += "/";
      this.inputF.setText(this.str);
      
      this.str1 = "0";
    }
    else if (this.c == 3)
    {
      this.ans *= this.x;
      this.str += "/";
      this.inputF.setText(this.str);
      
      this.str1 = "0";
    }
    else
    {
      this.str += "*";
      this.inputF.setText(this.str);
      this.str1 = "0";
    }
    this.c = 15;
  }
  
  private void itAnsActionPerformed(ActionEvent evt)
  {
    this.str = ("" + this.ans);
    this.inputF.setText(this.str);
  }
  
  public static void main(String[] args)
  {
    try
    {
      for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName()))
        {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (UnsupportedLookAndFeelException ex)
    {
      Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new NewJFrame().setVisible(true);
      }
    });
  }
}

